[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
compiler_version = "0.8.20"

[rpc_endpoints]
mumbai = "https://polygon-mumbai.infura.io/v3/YOUR_INFURA_KEY"
